name: Push
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: ./ci/deploy.sh
        env:
          NEXT_PUBLIC_API_URL: https://dev.kush-test.pp.ua
          NEXTAUTH_URL: https://dev.kush-test.pp.ua
          PREVIEW_SECRET: ${{ secrets.PREVIEW_SECRET }}
          NEXT_PUBLIC_URL: https://dev.kush-test.pp.ua
          NEXT_PUBLIC_STRAPI_URL: https://dev.kush-test.pp.ua/strapi/
          NEXTAUTH_SECRET: ${{ secrets.PREVIEW_SECRET }}
          ENV_NAME: dev
          GOOGLE_CLIENT_ID: 86751189471-8dcn81dhp8eorhnr13js6t9dr32ofl5n.apps.googleusercontent.com
          GOOGLE_CLIENT_SECRET: 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
